name: Build LLVM Pass

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install LLVM
      run: |
        sudo apt update
        sudo apt install -y llvm-14 clang-14 lld-14 cmake
    
    - name: Build pass
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
    
    - name: Test pass
      run: |
        cd build
        opt -load-pass-plugin ./librychkova_lab2_LLVM_IR.so -passes=muldiv_to_shift -S ../test.ll
